""" 
Exercise 
======== 
Starting with a copy of your code from problem 1a, modify it such that the 
powers 1 through 5 are generated by an implicit for loop. 

Note: This will require inserting a list comprehension. 
""" 

for i in range(1, 101): 
	print([i**j for j in range(1, 6)])  

